quiet: False
disable-version-string: True
with-expecter: True
mockname: "Mock{{.InterfaceName}}"
filename: "{{.MockName}}.go"
dir: "{{.PackageName}}"
inpackage: True
all: True
recursive: True
packages:
  github.com/mblancoa/authentication/core/ports:
    config:
      dir: "./core/ports"
#  github.com/mblancoa/authentication/tools:
#  github.com/mblancoa/authentication/adapters:
# Lots more config...