quiet: False
disable-version-string: True
with-expecter: True
mockname: "Mock{{.InterfaceName}}"
filename: "{{.MockName}}.go"
dir: "{{.PackageName}}"
inpackage: True
all: True
packages:
  github.com/mblancoa/authentication/core:
  github.com/mblancoa/authentication/tools:
#  github.com/mblancoa/authentication/adapter:
# Lots more config...