name: Development
run-name: ${{ github.actor }} is running Development workflow
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        
      - name: Update dependencies
        uses: actions/setup-go@v5
        
      #- name: Setup Mockery
      #  run: go install github.com/vektra/mockery/v2@v2.40.1
        
      - name: Generate mocks
        run: mockery

      - name: Test execution
        run: go test ./...

      - name: Clean
        run: make clean
 
