name: Development
run-name: ${{ github.actor }} is running Development workflow
on:
  push:
jobs:
  Push-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - name: Update dependencies
        run: go mod download
      - name: Code generation
        run: |
          go install github.com/sunboyy/repogen@latest
          go generate ./adapter/*
      - name: Mocks generation
        run: |
          go install github.com/vektra/mockery/v2@v2.40.1
          mockery
      - name: Tests execution
        run: |
          go clean -testcache
          make test
