name: Development
run-name: ${{ github.actor }} is running Development workflow
on: [push]
jobs:
  Push-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - name: Update dependencies
        run: go mod download
      - name: Code generation
        run: make code-generation
      - name: Setup Mockery
        run: go install github.com/vektra/mockery/v2@v2.40.1
      - name: Generate mocks
        run: mockery
      - name: Tests execution
        run: go test ./...
